version: '3'
volumes:
  shared-workspace:
    driver: local
services:
  spark-master:
    image: spark-local-spark-master
    container_name: spark-master
    ports:
      - 8080:8080
      - 7077:7077
    volumes:
      - shared-workspace:/opt/workspace
  spark-worker-1:
    image: spark-local-spark-worker
    container_name: spark-worker-1
    depends_on:
      - spark-master
    ports:
      - 8081:8081
    environment:
      - SPARK_WORKER_CORES=1
      - SPARK_WORKER_MEMORY=2048m
    volumes:
      - shared-workspace:/opt/workspace
  spark-worker-2:
    image: spark-local-spark-worker
    container_name: spark-worker-2
    depends_on:
      - spark-master
    ports:
      - 8082:8081
    environment:
      - SPARK_WORKER_CORES=1
      - SPARK_WORKER_MEMORY=2048m
    volumes:
      - shared-workspace:/opt/workspace
  jupyterlab:
    image: spark-local-jupyterlab
    container_name: spark-jupyterlab
    depends_on:
      - spark-master
    ports:
      - 8888:8888
    volumes:
      - shared-workspace:/opt/workspace