version: '3'
services:
  spark-master:
    image: zhujun/spark-local-master
    container_name: spark-master
    ports:
      - "8080:8080"
      - "7077:7077"
  spark-worker-1:
    image: zhujun/spark-local-worker
    container_name: spark-worker-1
    depends_on:
      - spark-master
    ports:
      - "8081:8081"
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
  spark-worker-2:
    image: zhujun/spark-local-worker
    container_name: spark-worker-2
    depends_on:
      - spark-master
    ports:
      - "8082:8081"
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"